jobs:
  include:
    - stage: Tests
      script: echo "'date' Unit Tests1" && sleep 5 ;exit 1
      name: "Unit Tests"
    - script: echo "'date' Integration-tests" && sleep 6
      name: "Intergration Tests"
    - stage: deploy
      name: "Deploy to GCP"
      script: echo "'date' Deploy to GCP"
    
